FORMAT: 1A
HOST: https://www.ez-khutbah.com/

# ez-khutbah

ez-khutbah is a simple API allowing consumers to CRUD khutbahs.

## Khutbahs Collection [api/v1/khutbah]

### List All Khutbah [GET]

+ Response 200 (application/json)

        [
            {
                "id": 10,
                "content": "### Best khutbah to date!!!",
                "published_at": "2017-10-10T08:40:51.620Z",
                "tags": [
                    "salawaat",
                    "sunnah"
                ],
                "ameen": 2
            },
            {
                "id": 6,
                "content": "### Older khutbah now....",
                "published_at": "2016-10-10T08:40:51.620Z",
                "tags": [
                    "tawheed"
                ],
                "ameen": 200
            }
        ]

### Create a New Khutbah [POST]

You may create your own khutbah using this action. It takes a JSON
object containing a khutbah. Returns a JSON object containing the 
publication datetime upon successful submission.

+ Request (application/json)

        {
            "content": "### New khutbah title\n\tSuper sweet khutbah here now",
            "tags": [
                "tawbah"
            ]
        }

+ Response 201 (application/json)

    + Body

            {
                "published_at": "2015-08-05T08:40:51.620Z",
            }
            
## Social interactions with Khutbah [api/v1/khutbah/:id/ameen]

### Ameen a Khutbah [POST]